# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05810be357f07654463f08d6ef17b1e4fc92ee4e7a59eedf18b3815c20aea15d3f41a583c5dd38902fb0cac316712b575afe29a883ec66f93032f6506adced74

test:
  secret_key_base: e172d57716a6448f9cba0929b2b635604ae4586d842b3b7da9f8479b37062a11cf4bfd80351fe15096cc2142cf4f64900aaa83a454cf1830375e3cdd6d9b23e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
